/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/asteroids': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get list of asteroids
         * @description Retrieve a paginated list of asteroids with their resources and mining status
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number for pagination (default: 1) */
                    page?: number;
                    /** @description Number of items per page */
                    perPage?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response with asteroid list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['AsteroidResponse'][];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/mine': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create mining operation
         * @description Start a new mining operation for specified asteroids
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': components['schemas']['MiningRequest'];
                };
            };
            responses: {
                /** @description Mining operation created successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['MiningResponse'];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BaseResource: {
            /** @description Unique resource identifier */
            id: string;
            /** @description Human-readable resource name */
            name: string;
        };
        MineralResource: components['schemas']['BaseResource'] & {
            /** @description Mass in tons */
            mass: number;
            /** @description Temperature in Kelvin */
            superconductingThreshold: number;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: 'mineral';
        };
        LiquidResource: components['schemas']['BaseResource'] & {
            /** @description Volume in liters */
            volume: number;
            /** @description Pressure in Pascals at which liquid evaporates */
            volatility: number;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: 'liquid';
        };
        GasResource: components['schemas']['BaseResource'] & {
            /** @description Volume in cubic meters */
            volume: number;
            /** @description Pressure in Pascals at which gas decomposes */
            volatility: number;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: 'gas';
        };
        Resource:
            | components['schemas']['MineralResource']
            | components['schemas']['LiquidResource']
            | components['schemas']['GasResource'];
        Asteroid: {
            /** @description Unique asteroid identifier */
            id: string;
            /** @description Human-readable asteroid name */
            name: string;
            /**
             * Format: date
             * @description Date of the asteroid's closest approach
             */
            approachDate: string;
            /** @description Asteroid diameter in meters */
            diameterMeters: number;
            /** @description Distance from Earth in kilometers */
            distanceKm: number;
            /** @description Distance from Earth in lunar distances */
            distanceLunar: number;
            /** @description List of resources available on the asteroid */
            resources: components['schemas']['Resource'][];
        };
        /**
         * @description Mining status of an asteroid
         * @enum {string}
         */
        AsteroidStatus: 'active' | 'done' | 'available';
        AsteroidResponse: components['schemas']['Asteroid'] & {
            status: components['schemas']['AsteroidStatus'];
        };
        MiningRequest: {
            /**
             * @description Array of asteroid IDs to mine
             * @example [
             *       "asteroid-001",
             *       "asteroid-002"
             *     ]
             */
            asteroids: string[];
        };
        /**
         * @description Status of a mining operation
         * @enum {string}
         */
        MiningStatus: 'active' | 'done';
        Mining: {
            /** @description Unique mining operation identifier */
            id: string;
            status: components['schemas']['MiningStatus'];
            /** @description Time to live in milliseconds */
            ttl: number;
        };
        MiningResponse: {
            /** @description Unique mining operation identifier */
            id: string;
            /** @description Array of asteroid IDs being mined */
            asteroids: string[];
        };
        Error: {
            /** @description Error message */
            error: string;
            /**
             * @description Error code
             * @example 400
             */
            code?: number;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['Error'];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['Error'];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['Error'];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
